apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: kubernetes:v1
          ports:
            - name: http
              containerPort: 3000
