apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kubernetes
  targetCPUUtilizationPercentage: 75
