apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  labels:
    app: kubernetes
spec:
  selector:
    app: kubernetes
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
